### ISSUE TITLE
Prevent fingerprint from sorting

### ISSUE THREAD

**Issue by david-raine-mns** [Yomguithereal/talisman#179]
Is there any way to use fingerprint without the final alphabetic sort phase? It looks like it uses a tokenizer that appears to have a "sort: true" in the options, but I can't seem to figure out how to pass that through.

**Comment by Yomguithereal** [comment]
Yes, there is a way, albeit undocumented (sorry about that :) ). You need to create your own tokenizer/keyer using the exported factory function thusly:

```js
import {createKeyer} from 'talisman/keyers/fingerprint';
// Or if you want to create a fingerprint tokenizer
import {createTokenizer} from 'talisman/tokenizers/fingerprint';

const fingerprint = createKeyer({sort: true});
```

The full list of options can be found [here](https://github.com/Yomguithereal/talisman/blob/master/src/tokenizers/fingerprint/index.js#L25-L30) if you need.

**Comment by david-raine-mns** [comment]
That is perfect and works a treat. Many thanks for this wonderful library.
