### ISSUE TITLE
Prevent the use of `.default` in imported modules

### ISSUE THREAD

**Issue by oncletom** [Yomguithereal/talisman#29]
Mostly linked to a behaviour change in babel@6.

> https://github.com/59naga/babel-plugin-add-module-exports

It is annoying only in Node 'cause the transpiled ES2015 import does get around it.

**Comment by Yomguithereal** [comment]
Hello @oncletom. Here is my dilemma concerning this behavior and node library lately:

CommonJS doesn't allow a combinaison of `exports` and `module.exports` so you cannot have both a default export and named ones. So the only existing trick is to `module.exports` an object, or in my case functions having static properties:

```js
function whatever() {}

whatever.somethingElseExported = 45;

module.exports = whatever;
```

While this works, this makes the resulting modules not possible to analyse statically and "break" ES6' modules' purpose. What's more, I think Babel doesn't support accessing false named exports in the export statement anymore, which means one could not do the following:

```js
// Not possible
import {relative} from 'talisman/stats/frequencies';

// You'll have to do
import freq from 'talisman/stats/frequencies';
const relative = freq.relative;
```

So I really don't know what to do here and will gladly take your insight on the subject :)

**Comment by Yomguithereal** [comment]
Any update on this @oncletom?

**Comment by oncletom** [comment]
Nah I have not checked but I think this will be address by the [Node ES6 module proposal](https://github.com/nodejs/node/wiki/ES6-Module-Detection-in-Node) so it it not worth spending time on "fixing" this.
