### ISSUE TITLE
Add "machine learning" to description

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/talisman#4]

**Comment by diegoantolinosbasso** [comment]
Okay, so dictionary look-up is a no-go but machine learning is fine ? I see what you did there...

**Comment by Yomguithereal** [comment]
Dictionary look-up is very fine. It's just that I cannot pack every dictionary known to humankind in this code module :).

**Comment by diegoantolinosbasso** [comment]
Can't you ?..
