### ISSUE TITLE
Bug jaroWinkler gives score > 1 for distinct strings

### ISSUE THREAD

**Issue by jfseb** [Yomguithereal/talisman#98]
Bug: distinct strings with common prefixes get a weight > 1.0
jaroWinkler('commonlongprefixword', 'commonlongprefixworm')

Created pull request: 

#97

**Comment by Yomguithereal** [comment]
This should be solved now (including the common prefix being limited to 4). Tell me if this fits you @jfseb and I'll release a patch on npm.

**Comment by jfseb** [comment]
fine, prefix limiting by 4 is also good. (saw this at natural, did not lookup original paper).

**Comment by Yomguithereal** [comment]
Just released v0.17.0 with the fix @jfseb.
